# Generated by Django 5.1.5 on 2025-04-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizar', '0003_alter_callpool_bulk_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callpool',
            name='bulk_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizar.bulk'),
        ),
        migrations.AlterField(
            model_name='test_callpool',
            name='bulk_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizar.test_bulk'),
        ),
    ]
