# Generated by Django 5.1.5 on 2025-04-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomizar', '0004_alter_callpool_bulk_table_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailycalllog',
            unique_together={('citrix_id', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='test_dailycalllog',
            unique_together={('citrix_id', 'date')},
        ),
        migrations.RemoveField(
            model_name='dailycalllog',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='test_dailycalllog',
            name='login_id',
        ),
    ]
